gallery/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.views.generic import RedirectView
#from photologue.sitemaps import GallerySitemap, PhotoSitemap

urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('', RedirectView.as_view(url='/photologue/', permanent=True)),
]
"""
sitemaps = {
    'photologue_galleries': GallerySitemap,
    'photologue_photos': PhotoSitemap,
}
"""

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/photologue/urls.py
from django.urls import path, re_path, reverse_lazy
from django.views.generic import RedirectView

from .views import (GalleryArchiveIndexView, GalleryDateDetailView, GalleryDayArchiveView, GalleryDetailView,
                    GalleryListView, GalleryMonthArchiveView, GalleryYearArchiveView, PhotoArchiveIndexView,
                    PhotoDateDetailView, PhotoDayArchiveView, PhotoDetailView, PhotoListView, PhotoMonthArchiveView,
                    PhotoYearArchiveView)

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""

app_name = 'photologue'
urlpatterns = [
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
            GalleryDateDetailView.as_view(month_format='%m'),
            name='gallery-detail'),
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
            GalleryDayArchiveView.as_view(month_format='%m'),
            name='gallery-archive-day'),
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
            GalleryMonthArchiveView.as_view(month_format='%m'),
            name='gallery-archive-month'),
    re_path(r'^gallery/(?P<year>\d{4})/$',
            GalleryYearArchiveView.as_view(),
            name='pl-gallery-archive-year'),
    path('gallery/',
         GalleryArchiveIndexView.as_view(),
         name='pl-gallery-archive'),
    path('',
         RedirectView.as_view(
             url=reverse_lazy('photologue:pl-gallery-archive'), permanent=True),
         name='pl-photologue-root'),
    re_path(r'^gallery/(?P<slug>[\-\d\w]+)/$',
            GalleryDetailView.as_view(), name='pl-gallery'),
    path('gallerylist/',
         GalleryListView.as_view(),
         name='gallery-list'),

    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
            PhotoDateDetailView.as_view(month_format='%m'),
            name='photo-detail'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
            PhotoDayArchiveView.as_view(month_format='%m'),
            name='photo-archive-day'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
            PhotoMonthArchiveView.as_view(month_format='%m'),
            name='photo-archive-month'),
    re_path(r'^photo/(?P<year>\d{4})/$',
            PhotoYearArchiveView.as_view(),
            name='pl-photo-archive-year'),
    path('photo/',
         PhotoArchiveIndexView.as_view(),
         name='pl-photo-archive'),

    re_path(r'^photo/(?P<slug>[\-\d\w]+)/$',
            PhotoDetailView.as_view(),
            name='pl-photo'),
    path('photolist/',
         PhotoListView.as_view(),
         name='photo-list'),
]

gallery/gallery/views.py
#
# encoding: utf-8
from django.shortcuts import render



def handler404(request, *args, **argv):
    return render(request, 'app.inc/404.html', status=404)


def handler500(request, *args, **argv):
    return render(request, 'app.inc/500.html', status=500)

gallery/gallery/templates/base.html
{% extends 'layout.html' %}
{% block navbar %}
	<div class="w3-bar w3-dark-light">
        <a href="/" class="w3-bar-item w3-button w3-large w3-wide w3-text-blue">
           <b>{{ APP_TITLE }}</b><br>
	       {#% block ss_title_bar %}<span class="w3-small w3-text-sand">{% block app_ss_title %}{{ APP_SUB_TITLE }}{% endblock %}</span>{% endblock %#}
	    </a>
	    {% block menubar %}
           {% block menubar-left %}{% include "menu-left.html" %}{% endblock %}
           {#% block menubar-right %}{% include "menu-right.html" %}{% endblock %#}
	    {% endblock  %}
	</div>
{% endblock %}
{% block main-content %}
    <div class="w3-container">
    {% block content %}{% endblock %}
    </div>
{% endblock %}
{% block footer %}
    {% include "app.inc/footer.html" %}
{% endblock  %}

gallery/gallery/templates/layout.html
{% load i18n %}
{% get_current_language as language_code %}
<!DOCTYPE html>
<html lang="{{ language_code|default:'fr_FR' }}">
    <head>
        <title>{% block title %}Django Automation{% endblock %}</title>
        <meta name="robots" content="{% block robots %}{% endblock %}" />
        <meta name="keywords" content="{% block keywords %}{% endblock %}" />
        <meta name="description" content="{% block description %}{% endblock %}" />
        <meta name="author" content="{% block author %}Auteur{% endblock %}">
        <!--meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"-->
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <link href="/static/img/logo.png" rel="shortcut icon">
		{% block styles %}
		<link href="/static/css/w3.css" rel="stylesheet">
		<link href="/static/css/all.min.css" rel="stylesheet">
		<link href="/static/css/w3-custom.css" rel="stylesheet">
		<link href="/static/css/styles.css" rel="stylesheet">
		{% endblock %}
        {% block js_header %}
        <script src="/static/js/jquery.min.js"></script>
        <script src="/static/js/w3-custom.js"></script>
        {% endblock %}
    </head>
    <body class="w3-black w3-no-margin">
        {% block main_layout %}
	        {% block navbar %}{% endblock  %}
	        <div id="topsite" style="max-width:1600px">
	            {% block header %}{% endblock  %}
	            {% block alert %}{% include 'app.inc/alert.html' %}{% endblock  %}
	            {% block main-content %}{% endblock %}
	        </div>
		    {% block footer %}{% endblock  %}
	        {% block js_footer %}{% endblock %}
        {% endblock %}
    </body>
</html>

gallery/gallery/templates/menu-left.html
{% load i18n %}
{% if not request.user.is_anonymous and request.user.is_active %}
	<div class="w3-dropdown-hover">
	    <button class="w3-button w3-dark-plus"><i class="fa-solid fa-eye w3-text-amber"></i> Toutes les vues</button>
	    <div class="w3-dropdown-content w3-bar-block w3-border w3-dark-light">
	        <div class="w3-bar-item w3-dark-plus"><i class="fa-solid fa-images w3-text-lime fa-2x"></i> Toutes les Galeries</div>
	        <a href="{% url 'photologue:pl-gallery-archive' %}" class="w3-bar-item w3-button">&nbsp;&nbsp;<i class="fa-solid fa-clock w3-text-teal"></i> Vues par date</a>
	        <a href="{% url 'photologue:gallery-list' %}" class="w3-bar-item w3-button">&nbsp;&nbsp;<i class="fa-solid fa-list w3-text-blue"></i> Vues en mode liste</a>

            <div class="w3-bar-item w3-dark-plus"><i class="fa-regular fa-id-card w3-text-lime fa-2x"></i> Toutes les Photographies</div>
            <a href="{% url 'photologue:pl-photo-archive' %}" class="w3-bar-item w3-button">&nbsp;&nbsp;<i class="fa-solid fa-clock w3-text-teal"></i> Vues par date</a>
            <a href="{% url 'photologue:photo-list' %}" class="w3-bar-item w3-button">&nbsp;&nbsp;<i class="fa-solid fa-list w3-text-blue"></i> Vues en mode liste</a>
	    </div>
	</div>
	<div class="w3-dropdown-hover">
	    <button class="w3-button  w3-dark-plus"><i class="fas fa-user-cog w3-text-amber"></i> <span>{{ request.user }}</span></button>
	    <div class="w3-dropdown-content w3-bar-block w3-border w3-dark-light">
	        {% if request.user.is_superuser %}
	        <a href="/admin/" class="w3-bar-item w3-button"><i class="fas fa-database w3-text-orange"></i> Database</a>
	        {% endif %}
	        {% if request.user.is_staff or request.user.is_superuser %}
	        <a href="/admin/photologue/photo/" class="w3-bar-item w3-button"><i class="fas fa-images w3-text-blue"></i> Photographies</a>
	        {% endif %}

	        <form method="post" action="{% url 'logout' %}">
	            {% csrf_token %}
	            <button class="w3-bar-item w3-button" type="submit"><i class="fas fa-sign-out-alt w3-text-red"></i> Déconnexion</button>
	        </form>
	    </div>
	</div>
{% endif %}

gallery/gallery/templates/menu-right.html
{% load i18n %}
{% if not request.user.is_anonymous and request.user.is_active or request.user.is_superuser %}
<div class="w3-dropdown-hover w3-right">
    <button class="w3-button "><i class="fas fa-user-cog w3-text-amber"></i> <span>{{ request.user }}&nbsp; &#9776;</span></button>
    <div class="w3-dropdown-content w3-bar-block w3-border w3-dark-medium" style="right:.1em;">
        {% if request.user.is_staff %}
        <a href="/admin/" class="w3-bar-item w3-button"><i class="fas fa-database w3-text-orange"></i> Base de données</a>
        <a href="/admin/photologue/photo/" class="w3-bar-item w3-button"><i class="fas fa-images w3-text-blue"></i> Accès photographies</a>
        {% endif %}
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button class="w3-bar-item w3-button" type="submit"><i class="fas fa-sign-out-alt w3-text-red"></i> Déconnexion</button>
        </form>

    </div>
</div>
{% endif %}