gallery/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.views.generic import RedirectView
#from photologue.sitemaps import GallerySitemap, PhotoSitemap

urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('', RedirectView.as_view(url='/photologue/', permanent=True)),
]
"""
sitemaps = {
    'photologue_galleries': GallerySitemap,
    'photologue_photos': PhotoSitemap,
}
"""

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/photologue/urls.py
from django.urls import path, re_path, reverse_lazy
from django.views.generic import RedirectView

from .views import (GalleryArchiveIndexView, GalleryDateDetailView, GalleryDayArchiveView, GalleryDetailView,
                    GalleryListView, GalleryMonthArchiveView, GalleryYearArchiveView, PhotoArchiveIndexView,
                    PhotoDateDetailView, PhotoDayArchiveView, PhotoDetailView, PhotoListView, PhotoMonthArchiveView,
                    PhotoYearArchiveView)

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""

app_name = 'photologue'
urlpatterns = [
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
            GalleryDateDetailView.as_view(month_format='%m'),
            name='gallery-detail'),
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
            GalleryDayArchiveView.as_view(month_format='%m'),
            name='gallery-archive-day'),
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
            GalleryMonthArchiveView.as_view(month_format='%m'),
            name='gallery-archive-month'),
    re_path(r'^gallery/(?P<year>\d{4})/$',
            GalleryYearArchiveView.as_view(),
            name='pl-gallery-archive-year'),
    path('gallery/',
         GalleryArchiveIndexView.as_view(),
         name='pl-gallery-archive'),
    path('',
         RedirectView.as_view(
             url=reverse_lazy('photologue:pl-gallery-archive'), permanent=True),
         name='pl-photologue-root'),
    re_path(r'^gallery/(?P<slug>[\-\d\w]+)/$',
            GalleryDetailView.as_view(), name='pl-gallery'),
    path('gallerylist/',
         GalleryListView.as_view(),
         name='gallery-list'),

    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
            PhotoDateDetailView.as_view(month_format='%m'),
            name='photo-detail'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
            PhotoDayArchiveView.as_view(month_format='%m'),
            name='photo-archive-day'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
            PhotoMonthArchiveView.as_view(month_format='%m'),
            name='photo-archive-month'),
    re_path(r'^photo/(?P<year>\d{4})/$',
            PhotoYearArchiveView.as_view(),
            name='pl-photo-archive-year'),
    path('photo/',
         PhotoArchiveIndexView.as_view(),
         name='pl-photo-archive'),

    re_path(r'^photo/(?P<slug>[\-\d\w]+)/$',
            PhotoDetailView.as_view(),
            name='pl-photo'),
    path('photolist/',
         PhotoListView.as_view(),
         name='photo-list'),
]

gallery/photologue/forms.py
import logging
import os
import zipfile
from io import BytesIO
from typing import List
from zipfile import BadZipFile

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.messages import constants
from django.contrib.sites.models import Site
from django.core.files.base import ContentFile
from django.template.defaultfilters import slugify
from django.utils.encoding import force_str
from django.utils.translation import gettext_lazy as _
from PIL import Image

from .models import Gallery, Photo

logger = logging.getLogger('photologue.forms')

MessageSeverity = int
MessageContent = str


class PhotoDefaults:
    title: str
    caption: str
    is_public: bool

    def __init__(self, title: str, caption: str, is_public: bool) -> "PhotoDefaults":
        self.title = title
        self.caption = caption
        self.is_public = is_public


class UploadMessage:
    severity: MessageSeverity
    content: MessageContent

    def __init__(self, severity: MessageSeverity, content: MessageContent) -> "UploadMessage":
        self.severity = severity
        self.content = content

    def success(content: MessageContent):  # @NoSelf
        return UploadMessage(severity=constants.SUCCESS, content=content)

    def warning(content: MessageContent):  # @NoSelf
        return UploadMessage(severity=constants.WARNING, content=content)


class UploadZipForm(forms.Form):
    zip_file = forms.FileField()

    title = forms.CharField(label=_('Title'),
                            max_length=250,
                            required=False,
                            help_text=_('All uploaded photos will be given a title made up of this title + a '
                                        'sequential number.<br>This field is required if creating a new '
                                        'gallery, but is optional when adding to an existing gallery - if '
                                        'not supplied, the photo titles will be creating from the existing '
                                        'gallery name.'))
    gallery = forms.ModelChoiceField(Gallery.objects.all(),
                                     label=_('Gallery'),
                                     required=False,
                                     help_text=_('Select a gallery to add these images to. Leave this empty to '
                                                 'create a new gallery from the supplied title.'))
    caption = forms.CharField(label=_('Caption'),
                              required=False,
                              help_text=_('Caption will be added to all photos.'))
    description = forms.CharField(label=_('Description'),
                                  required=False,
                                  help_text=_('A description of this Gallery. Only required for new galleries.'))
    is_public = forms.BooleanField(label=_('Is public'),
                                   initial=True,
                                   required=False,
                                   help_text=_('Uncheck this to make the uploaded '
                                               'gallery and included photographs private.'))

    def clean_zip_file(self):
        """Open the zip file a first time, to check that it is a valid zip archive.
        We'll open it again in a moment, so we have some duplication, but let's focus
        on keeping the code easier to read!
        """
        zip_file = self.cleaned_data['zip_file']
        try:
            zipf = zipfile.ZipFile(zip_file)  # @UnusedVariable
        except BadZipFile as e:
            raise forms.ValidationError(str(e))
        bad_file = zipf.testzip()
        if bad_file:
            zipf.close()
            raise forms.ValidationError('"%s" in the .zip archive is corrupt.' % bad_file)
        zipf.close()  # Close file in all cases.
        return zip_file

    def clean_title(self):
        title = self.cleaned_data['title']
        if title and Gallery.objects.filter(title=title).exists():
            raise forms.ValidationError(_('A gallery with that title already exists.'))
        return title

    def clean(self):
        cleaned_data = super().clean()
        if not self['title'].errors:
            # If there's already an error in the title, no need to add another
            # error related to the same field.
            if not cleaned_data.get('title', None) and not cleaned_data['gallery']:
                raise forms.ValidationError(
                    _('Select an existing gallery, or enter a title for a new gallery.'))
        return cleaned_data

    def save(self, request=None, zip_file=None):
        if not zip_file:
            zip_file = self.cleaned_data['zip_file']

        zipf = zipfile.ZipFile(zip_file)  # @UnusedVariable
        photo_defaults = PhotoDefaults(
            title=self.cleaned_data["title"], caption=self.cleaned_data["caption"],
            is_public=self.cleaned_data["is_public"])
        current_site = Site.objects.get(id=settings.SITE_ID)

        gallery = self._reuse_or_create_gallery_in_site(current_site)

        upload_messages = upload_photos_to_site(current_site, zipf, gallery, photo_defaults)

        if request:
            for upload_message in upload_messages:
                messages.add_message(request, upload_message.severity, upload_message.content, fail_silently=True)

    def _reuse_or_create_gallery_in_site(self, current_site):
        if self.cleaned_data['gallery']:
            logger.debug('Using pre-existing gallery.')
            gallery = self.cleaned_data['gallery']
        else:
            logger.debug(
                force_str('Creating new gallery "{0}".').format(self.cleaned_data['title']))
            gallery = create_gallery_in_site(current_site,
                                             title=self.cleaned_data['title'],
                                             description=self.cleaned_data['description'],
                                             is_public=self.cleaned_data['is_public'])

        return gallery


def create_gallery_in_site(site: Site, title: str, description: str = "", is_public: bool = False) -> Gallery:
    gallery = Gallery.objects.create(title=title,
                                     slug=slugify(title),
                                     description=description,
                                     is_public=is_public)
    gallery.sites.add(site)
    return gallery


def upload_photos_to_site(site: Site, zipf: zipfile.ZipFile, gallery: Gallery, photo_defaults: PhotoDefaults)\
        -> List[UploadMessage]:
    upload_messages = []
    count = 1

    for filename in sorted(zipf.namelist()):

        logger.debug(f'Reading file "{filename}".')

        if filename.startswith('__') or filename.startswith('.'):
            logger.debug(f'Ignoring file "{filename}".')
            continue

        if os.path.dirname(filename):
            logger.warning('Ignoring file "{}" as it is in a subfolder; all images should be in the top '
                           'folder of the zip.'.format(filename))
            upload_messages.append(UploadMessage.warning(
                _('Ignoring file "{filename}" as it is in a subfolder; all images should be in the top folder of the '
                  'zip.').format(filename=filename)))
            continue

        data = zipf.read(filename)

        if not len(data):
            logger.debug(f'File "{filename}" is empty.')
            continue

        photo_title_root = photo_defaults.title if photo_defaults.title else gallery.title

        # A photo might already exist with the same slug. So it's somewhat inefficient,
        # but we loop until we find a slug that's available.
        while True:
            photo_title = ' '.join([photo_title_root, str(count)])
            slug = slugify(photo_title)
            if Photo.objects.filter(slug=slug).exists():
                count += 1
                continue
            break

        photo = Photo(title=photo_title,
                      slug=slug,
                      caption=photo_defaults.caption,
                      is_public=photo_defaults.is_public)

        # Basic check that we have a valid image.
        try:
            file = BytesIO(data)
            opened = Image.open(file)
            opened.verify()
        except Exception:
            # Pillow doesn't recognize it as an image.
            # If a "bad" file is found we just skip it.
            # But we do flag this both in the logs and to the user.
            logger.error('Could not process file "{}" in the .zip archive.'.format(
                filename))
            upload_messages.append(UploadMessage.warning(
                _('Could not process file "{0}" in the .zip archive.').format(filename)))
            continue

        contentfile = ContentFile(data)
        photo.image.save(filename, contentfile)
        photo.save()
        photo.sites.add(site)
        gallery.photos.add(photo)
        count += 1

    zipf.close()

    upload_messages.append(UploadMessage.success(
        _('The photos have been added to gallery "{0}".').format(gallery.title)))

    return upload_messages

gallery/photologue/views.py
from django.views.generic.dates import (ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView,
                                        YearArchiveView)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Gallery, Photo

# Gallery views.


class GalleryListView(ListView):
    queryset = Gallery.objects.on_site().is_public()
    paginate_by = 20


class GalleryDetailView(DetailView):
    queryset = Gallery.objects.on_site().is_public()


class GalleryDateView:
    queryset = Gallery.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class GalleryDateDetailView(GalleryDateView, DateDetailView):
    pass


class GalleryArchiveIndexView(GalleryDateView, ArchiveIndexView):
    pass


class GalleryDayArchiveView(GalleryDateView, DayArchiveView):
    pass


class GalleryMonthArchiveView(GalleryDateView, MonthArchiveView):
    pass


class GalleryYearArchiveView(GalleryDateView, YearArchiveView):
    make_object_list = True

# Photo views.


class PhotoListView(ListView):
    queryset = Photo.objects.on_site().is_public()
    paginate_by = 20


class PhotoDetailView(DetailView):
    queryset = Photo.objects.on_site().is_public()


class PhotoDateView:
    queryset = Photo.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True

gallery/templates/photologue/gallery_archive.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photo galleries" %}{% endblock %}
{% block app_ss_title %}{% trans "Latest photo galleries" %}{% endblock %}

{% block content %}
	<div class="w3-row">
	    <div class="w3-col l12">
	        <h2 class="w3-border-bottom">{% trans "Latest photo galleries" %}</h2>
	    </div>
	</div>
	<div class="w3-row">
	    <aside class="w3-col l2">
	        <h4>{% trans "Filter by year" %}</h4>
	        <ul>
	            {% for date in date_list %}
	            <li><a href="{% url 'photologue:pl-gallery-archive-year' date.year %}" class="w3-button w3-dark-light">{{ date|date:"Y" }}</a></li>
	            {% endfor %}
	        </ul>
	    </aside>
	    <main class="w3-col l10">
	        {% if latest %}
	        {% for gallery in latest %}
	        {% include "photologue/includes/gallery_sample.html" %}
	        {% endfor %}
	        {% else %}
	        <p>{% trans "No galleries were found" %}.</p>
	        {% endif %}
	    </main>
	</div>
{% endblock %}

gallery/templates/photologue/gallery_archive_day.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}
    <div class="w3-row">
        <div class="w3-col l12">
            <h1>{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}</h1>
        </div>
    </div>
    <div class="w3-row">
        <div class="w3-col l12">
        {% if object_list %}
            {% for gallery in object_list %}
                {% include "photologue/includes/gallery_sample.html" %}
            {% endfor %}
        {% else %}
            <p>{% trans "No galleries were found." %}</p>
        {% endif %}
        </div>
    </div>

    <div><a href="{% url 'photologue:gallery-archive-month' day.year day|date:"m"|lower %}" class="btn btn-outline-secondary">{% trans "View all galleries for month" %}</a></div>

{% endblock %}

gallery/templates/photologue/gallery_archive_month.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}
    <div class="w3-row">
        <div class="w3-col l12">
            <h1>{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}</h1>
        </div>
    </div>
    <div class="w3-row">
        <aside class="w3-col l2">
            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:gallery-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>
        <main class="w3-col l10">
            {% if object_list %}
                {% for gallery in object_list %}
                    {% include "photologue/includes/gallery_sample.html" %}
                {% endfor %}
            {% else %}
                <p>{% trans "No galleries were found." %}</p>
            {% endif %}
            <div><a href="{% url 'photologue:pl-gallery-archive-year' month.year %}" class="btn btn-outline-secondary">{% trans "View all galleries for year" %}</a></div>
        </main>
    </div>

{% endblock %}

gallery/templates/photologue/gallery_archive_year.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}
    <div class="w3-row">
		<div class="w3-col l12">
        	<h1>{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}</h1>
    	</div>
	</div>
	<div class="w3-row">
		<aside class="w3-col l2">
			<h4>{% trans "Filter by month" %}</h4>
			<ul>
				{% for date in date_list %}
					<li><a href="{% url 'photologue:gallery-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
				{% endfor %}
			</ul>
		</aside>
		<main class="w3-col l10">
			{% if object_list %}
				{% for gallery in object_list %}
			        {% include "photologue/includes/gallery_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>{% trans "No galleries were found." %}</p>
			{% endif %}
		    <div><a href="{% url 'photologue:pl-gallery-archive' %}" class="btn btn-outline-secondary">{% trans "View all galleries" %}</a></div>
		</main>
	</div>
{% endblock %}

gallery/templates/photologue/gallery_detail.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{{ gallery.title }}{% endblock %}

{% block content %}
<div class="w3-row">
    <div class="w3-col l12">
        <h1>{{ gallery.title }}</h1>
        <p class="w3-text-grey w3-small">{% trans "Published" %} {{ gallery.date_added }}</p>
        {% if gallery.description %}{{ gallery.description|safe }}{% endif %}
        <div class="gallery-list">
            {% for photo in gallery.public %}
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
            </a>
            {% endfor %}
        </div>
        <div>
            <a href="{% url 'photologue:gallery-list' %}" class="w3-button w3-dark-light w3-margin-top">{% trans "View all galleries" %}</a>
        </div>
    </div>
</div>
{% endblock %}

gallery/templates/photologue/gallery_list.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "All galleries" %}{% endblock %}
{% block app_ss_title %}{% trans "All galleries" %}{% endblock %}

{% block content %}
	<div class="w3-row">
	    <div class="w3-col l12">
	        <h1>{% trans "All galleries" %}</h1>
	    </div>
	</div>
	{% if object_list %}
	{% for gallery in object_list %}
	<div class="w3-row">
	    <div class="w3-col l12">
	        {% include "photologue/includes/gallery_sample.html" %}
	    </div>
	</div>
	{% endfor %}
	{% else %}
	<div class="w3-row">
	    <div class="w3-col l12">{% trans "No galleries were found" %}.</div>
	</div>
	{% endif %}

	{% include "photologue/includes/paginator.html" %}

{% endblock %}

gallery/templates/photologue/photo_archive.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photos" %}{% endblock %}
{% block app_ss_title %}{% trans "Latest photos" %}{% endblock %}
{% block content %}
	<div class="w3-row">
	    <div class="w3-col l12">
	        <h1>{% trans "Latest photos" %}</h1>
	    </div>
	</div>
	<div class="w3-row">
	    <aside class="w3-col m2">
	        <h4>{% trans "Filter by year" %}</h4>
	        <ul>
	            {% for date in date_list %}
	            <li><a href="{% url 'photologue:pl-photo-archive-year' date.year %}" class="w3-button w3-dark-light">{{ date|date:"Y" }}</a></li>
	            {% endfor %}
	        </ul>
	    </aside>
	    <main class="w3-col m10 photo-list">
	        {% if latest %}
	        {% for photo in latest %}
	        <a href="{{ photo.get_absolute_url }}">
	            <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
	        </a>
	        {% endfor %}
	        {% else %}
	        <p>{% trans "No photos were found" %}.</p>
	        {% endif %}
	    </main>
	</div>
{% endblock %}

gallery/templates/photologue/photo_archive_day.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}
    <div class="w3-row">
		<div class="w3-col l12">
        	<h1>{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}</h1>
		</div>
	</div>
	{% if object_list %}
		<div class="w3-row">
			<div class="w3-col l12">
		    {% for photo in object_list %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
		        </a>
		    {% endfor %}
			</div>
		</div>
	{% else %}
		<p>{% trans "No photos were found" %}.</p>
	{% endif %}
    <div><a href="{% url 'photologue:photo-archive-month' day.year day|date:"m"|lower %}" class="btn btn-outline-secondary">{% trans "View all photos for month" %}</a></div>
{% endblock %}

gallery/templates/photologue/photo_archive_month.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}
    <div class="w3-row">
        <div class="w3-col l12">
            <h1>{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}</h1>
        </div>
    </div>
    <div class="w3-row">
        <aside class="col m2">
            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:photo-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>
        </aside>
        <main class="w3-col m10">
    		{% if object_list %}
    			<div class="w3-row">
                    <div class="w3-col l12">
    			    {% for photo in object_list %}
    			        <a href="{{ photo.get_absolute_url }}">
    			             <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
    			        </a>
    			    {% endfor %}
                    </div>
    			</div>
    		{% else %}
    			<p>{% trans "No photos were found" %}.</p>
    		{% endif %}
            <div><a href="{% url 'photologue:pl-photo-archive-year' month.year %}" class="btn btn-outline-secondary">{% trans "View all photos for year" %}</a></div>
        </main>
    </div>
{% endblock %}

gallery/templates/photologue/photo_archive_year.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}{% endblock %}


{% block content %}
    <div class="w3-row">
		<div class="w3-col l12">
        	<h1>{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}</h1>
    	</div>
	</div>
	<div class="w3-row">
		<aside class="w3-col m2">
			<h4>{% trans "Filter by month" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'photologue:photo-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
			{% endfor %}
			</ul>
		</aside>
		<main class="w3-col m10">
			{% if object_list %}
				<div class="w3-row">
					<div class="w3-col l12">
				    {% for photo in object_list %}
				        <a href="{{ photo.get_absolute_url }}">
				             <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
				        </a>
				    {% endfor %}
					</div>
				</div>
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %}
		    <div><a href="{% url 'photologue:pl-photo-archive' %}" class="btn btn-outline-secondary">{% trans "View all photos" %}</a></div>
		</main>
	</div>
{% endblock %}

gallery/templates/photologue/photo_detail.html
{% extends "photologue/root.html" %}
{% load photologue_tags i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
	<div class="w3-row">
	    <div class="w3-col l12">
	        <h1>{{ object.title }}</h1>
	        <p class="text-muted small">{% trans "Published" %} {{ object.date_added }}</p>
	    </div>
	</div>
	<div class="w3-row">
	    <div class="w3-col m6">
	        {% if object.caption %}<p>{{ object.caption }}</p>{% endif %}
	        <a href="{{ object.image.url }}">
	            <img src="{{ object.get_display_url }}" class="img-thumbnail" alt="{{ object.title }}">
	        </a>
	    </div>
	    <div class="w3-col m6">
	        {% if object.public_galleries %}
	        <p>{% trans "This photo is found in the following galleries" %}:</p>
	        <table>
	            {% for gallery in object.public_galleries %}
	            <tr>
	                <td>{% previous_in_gallery object gallery %}</td>
	                <td class="w3-center"><a href="{{ gallery.get_absolute_url }}" class="w3-button w3-dark-light">{{ gallery.title }}</a></td>
	                <td>{% next_in_gallery object gallery %}</td>
	            </tr>
	            {% endfor %}
	        </table>
	        {% endif %}
	    </div>
	</div>
{% endblock %}

gallery/templates/photologue/photo_list.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "All photos" %}{% endblock %}
{% block app_ss_title %}{% trans "All photos" %}{% endblock %}
{% block content %}
	<div class="w3-row">
	    <div class="w3-col l12">
	        <h1>{% trans "All photos" %}</h1>
	    </div>
	</div>
	{% if object_list %}
	<div class="w3-row">
	    <div class="w3-col l12 photo-list">
	        {% for photo in object_list %}
	        <a href="{{ photo.get_absolute_url }}">
	            <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
	        </a>
	        {% endfor %}
	    </div>
	</div>
	{% else %}
	<div class="w3-row">
	   <div class="w3-col l12">{% trans "No photos were found" %}.</div>
	</div>
	{% endif %}
	{% include "photologue/includes/paginator.html" %}
{% endblock %}

gallery/templates/photologue/root.html
{% extends "base.html" %}